// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd0B57Myiev_-TFe7-nqPXKdPvxeI2bz0',
    appId: '1:683394375104:web:1a8485dc41a61aa07a3c25',
    messagingSenderId: '683394375104',
    projectId: 'baby-evie-countdown',
    authDomain: 'baby-evie-countdown.firebaseapp.com',
    storageBucket: 'baby-evie-countdown.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2FlLST79fbZCK6bl4gEOPoGBDTGOtfWE',
    appId: '1:683394375104:android:3063eb6f9059c7dc7a3c25',
    messagingSenderId: '683394375104',
    projectId: 'baby-evie-countdown',
    storageBucket: 'baby-evie-countdown.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWm7qlJxUjwuEPeQC_UiSCJnh0rIx7Los',
    appId: '1:683394375104:ios:0910cf6ef43821967a3c25',
    messagingSenderId: '683394375104',
    projectId: 'baby-evie-countdown',
    storageBucket: 'baby-evie-countdown.firebasestorage.app',
    iosBundleId: 'com.example.laborNotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWm7qlJxUjwuEPeQC_UiSCJnh0rIx7Los',
    appId: '1:683394375104:ios:0910cf6ef43821967a3c25',
    messagingSenderId: '683394375104',
    projectId: 'baby-evie-countdown',
    storageBucket: 'baby-evie-countdown.firebasestorage.app',
    iosBundleId: 'com.example.laborNotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd0B57Myiev_-TFe7-nqPXKdPvxeI2bz0',
    appId: '1:683394375104:web:1a8485dc41a61aa07a3c25',
    messagingSenderId: '683394375104',
    projectId: 'baby-evie-countdown',
    authDomain: 'baby-evie-countdown.firebaseapp.com',
    storageBucket: 'baby-evie-countdown.firebasestorage.app',
  );
}